trunk/EasyDoc/Cardinal.EasyApps.ED.Caratulas/App/Cardinal.EasyApps.Caratulas/EasyApps.ED.Caratulas.WebRazor/Areas/Api1/Controllers/CaratulasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Cardinal.EasyApps.ED.Common.Dal;
using Cardinal.EasyApps.ED.Model;


namespace Cardinal.EasyApps.ED.Caratulas.WebRazor.Areas.Api1.Controllers
{
    public class CaratulasController : Controller
    {
        
        IRepository _repository;
        public CaratulasController(IRepository repository)
        {
            _repository = repository;
        	
        }

           [HttpPost]
        public ActionResult Caratulas(string loginToken)
        {
            return new JsonResult
            {
                Data = _repository.GetCaratulas().ToList()
            };
        }

           [HttpPost]
           public ActionResult Inbound(string loginToken,int dias)
           {
               return new JsonResult
               {
                   Data = _repository.GetCaratulas().Where(p=> p.FechaInbound >= DateTime.Now.AddDays(-30)).ToList()
               };
           }

             [HttpPost]
           public ActionResult RealizarInbound(string loginToken, long numeroCaratula)
        {
            _repository.RealizarInbound(numeroCaratula);

            return new JsonResult
            {
                Data = string.Empty
            };
        }

        [HttpPost]
        public ActionResult CaratulasByUser(string loginToken, string username)
        {
            return new JsonResult
            {
            Data = _repository.GetCaratulas(username).ToList()
            };
        }

    }
}

trunk/EasyDoc/Cardinal.EasyApps.ED.Caratulas/App/Cardinal.EasyApps.Caratulas/EasyApps.ED.Caratulas.WebRazor/Controllers/CaratulaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Collections;
using Telerik.Web.Mvc;
using System.Text;
using Telerik.Reporting.Processing;
using Cardinal.EasyApps.ED.Model;
using Cardinal.EasyApps.ED.Common.Dal;
using System.Configuration;

namespace Cardinal.Caratulas.Controllers
{
    [Authorize]
    public class CaratulaController : Controller
    {
        Cardinal.EasyApps.ED.Common.Dal.IRepository _repository;

        public CaratulaController(IRepository repository)
        {
            _repository = repository;
        }

        public JsonResult _GetPlantillas(string codEmpresa)
        {
            var plantillas = ConexionServiciosED.GetPlantillasByEmpresaJSON((LoginAuth)Session["TokenTicket"], codEmpresa);

            return Json(new SelectList(plantillas, "CodigoPlantilla", "Nombre"), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            ViewBag.Controles = "";

            // SelectList lista = new SelectList(, "CodigoCliente", "Nombre");
            ViewBag.Empresas = ConexionServiciosED.GetEmpresasJSON((LoginAuth)Session["TokenTicket"]);
            Session["EmpresasJSON"] = ViewBag.Empresas;
         
            _repository.LogOperationCaratulas(new LogCaratula { CD_MOVIMIENTO = 1, CD_USUARIO_MOVIMIENTO = Session["UserName"].ToString(), FC_MOVIMIENTO = DateTime.Now, TX_OBSERVACION = "Se consulto" });
     
            // ViewBag.PlantillaPorEmpresaServiceJSONURL = ConfigurationManager.AppSettings["PlantillaPorEmpresaServiceJSON"].ToString();
            return View();
        }

        public ActionResult GetCamposPlantilla(string plantillaId)
        {
            var camposPlantillas = ConexionServiciosED.GetCamposByPlantillaJSON((LoginAuth)Session["TokenTicket"], plantillaId);
            return PartialView("_CamposPlantilla", camposPlantillas);
        }

        [HttpPost]
        public ActionResult CreateCaratula()
        {
            if (string.IsNullOrWhiteSpace(Request.Form["Plantilla"]))
            {
                ModelState.AddModelError("Plantilla", "Por favor Seleccione una Plantilla.");
            }

            //Valido Campos

            var plantillaId = Request.Form["Plantilla"];
            var empresaId = Request.Form["Empresa"];

            var plantilla =
            ConexionServiciosED.GetPlantillasByEmpresaJSON((LoginAuth)Session["TokenTicket"], empresaId)
                               .Where(p => p.CodigoPlantilla == plantillaId)
                               .FirstOrDefault();
            var camposPlantillas = ConexionServiciosED.GetCamposByPlantillaJSON((LoginAuth)Session["TokenTicket"], plantillaId);

            foreach (var item in camposPlantillas.Where(p => p.EsCampoDetalle == false))
            {
                if (item.EsObligatorio)
                {
                    var valorCampo = Request.Form[item.CampoId];
                    if (string.IsNullOrWhiteSpace(valorCampo))
                    {
                        ModelState.AddModelError(item.CampoId, String.Format("Por favor ingrese un valor para el campo {0}.", item.Nombre));
                    }
                }
            }

            if (ModelState.IsValid)
            {
                int IDDocumentoMax = 0;

                List<CamposCS> listaCampos = new List<CamposCS>();
                DocumentoEmpresa documento = new DocumentoEmpresa
                {
                    empresa = ConexionServiciosED.GetEmpresasJSON((LoginAuth)Session["TokenTicket"]).Where(p => p.CodigoCliente == empresaId).FirstOrDefault(),
                    estadoDocumento = "1",
                    fechaCreacion = DateTime.Now,
                    usuarioCarga = User.Identity.Name,
                    codigoDocumento = IDDocumentoMax
                };
                foreach (var item in camposPlantillas.Where(p => p.EsCampoDetalle == false))
                {
                    CamposCS campo = new CamposCS
                    {
                        campo = item.CampoId, valor = Request.Form[item.CampoId], txCampo = item.Nombre,
                        EsDetalle = false, OrdenDetalle = 0
                    };
                    listaCampos.Add(campo);
                }

                documento.listaCampos = listaCampos;
                documento.plantilla = plantillaId;
                documento.txPlantilla = plantilla.Nombre;
                documento.codigo3d = generarValores3d(IDDocumentoMax, listaCampos);

                //Cargo los Detalles 
                foreach (var item in camposPlantillas.Where(p => p.EsCampoDetalle == true))
                {
                    CamposCS campo = new CamposCS
                    {
                        campo = item.CampoId,
                        valor = Request.Form[item.CampoId],
                        txCampo = item.Nombre,
                        EsDetalle = true
                    };
                    listaCampos.Add(campo);

                    short i = 1;
                    bool seguir = !String.IsNullOrWhiteSpace(Request.Form[String.Format("{0}{1}", item.CampoId, i)]);
                    while (seguir)
                    {
                        CamposCS campoDetalle = new CamposCS
                        {
                            campo = String.Format("{0}_{1}", item.CampoId, i),
                            valor = Request.Form[String.Format("{0}{1}", item.CampoId, i)],
                            txCampo = item.Nombre,
                            EsDetalle = true,
                            OrdenDetalle = i
                        };
                        listaCampos.Add(campoDetalle);
                        i++;
                        seguir = !String.IsNullOrWhiteSpace(Request.Form[String.Format("{0}{1}", item.CampoId, i)]);
                    }
                }

                var numDoc = _repository.saveDocumento(documento);

                //Session["Documento"] = documento.codigoDocumento;
                _repository.LogOperationCaratulas(new LogCaratula { CD_MOVIMIENTO = 1, CD_USUARIO_MOVIMIENTO = Session["UserName"].ToString(), FC_MOVIMIENTO = DateTime.Now, TX_OBSERVACION = "Se dió de alta el siguiente documento " + documento.codigo3d });
                //return RedirectToAction("Index", "Message", new { message = "El documento fue creado con éxito" });
                return RedirectToAction("VerReporte", "Historico", new { id = numDoc });
            }
            else
            {
                return ErroCargaCaratula();
            }
        }

        private ActionResult ErroCargaCaratula()
        {
            ViewBag.Empresas = ConexionServiciosED.GetEmpresasJSON((LoginAuth)Session["TokenTicket"]);
            Session["EmpresasJSON"] = ViewBag.Empresas;

            //Debo Guardar Empresa, Plantilla

            return View("Create");
        }

        private string generarValores3d(int IDDocumentoMax, List<CamposCS> listaCampos)
        {
            StringBuilder sb3d = new StringBuilder();
            sb3d.Append(IDDocumentoMax);
            sb3d.Append(",");
            foreach (CamposCS item in listaCampos)
            {
                sb3d.Append(item.valor);
                sb3d.Append(",");
            }
            return sb3d.ToString();
        }

        public ActionResult GetPdfCaratula(int caratulaId)
        {
            Cardinal.EasyApps.ED.Caratulas.WebRazor.Reportes.CaratulaReport reporte = new Cardinal.EasyApps.ED.Caratulas.WebRazor.Reportes.CaratulaReport();

           var data = _repository.GetCaratulaVistaPorId(caratulaId);

           reporte.ReportParameters["Empresa"].Value = data.nombre_empresa;
            reporte.ReportParameters["Plantilla"].Value = data.plantilla;
            reporte.ReportParameters["Usuario"].Value = data.usuario;
            reporte.ReportParameters["Fecha"].Value = data.fecha;
         


            reporte.DataSource = data.DetalleCampos;
            MessagingToolkit.QRCode.Codec.QRCodeEncoder qr = new MessagingToolkit.QRCode.Codec.QRCodeEncoder();
            string str = data.codigo_3d;//(reporte.Items.Find("codigo_3d_not_visible", true)[0] as Telerik.Reporting.TextBox).Value;
            System.Drawing.Bitmap bmp = qr.Encode(str);
            (reporte.Items.Find("picBoxQR", true)[0] as Telerik.Reporting.PictureBox).Value = bmp;

            //BarCode Caratula
            (reporte.Items.Find("barcode2", true)[0] as Telerik.Reporting.Barcode).Value = data.codigo.ToString();

            ReportProcessor reportProcessor = new ReportProcessor();
            RenderingResult result = reportProcessor.RenderReport("PDF", reporte, null);
            return File(result.DocumentBytes, System.Net.Mime.MediaTypeNames.Application.Pdf, String.Format("Caratula {0}.pdf", caratulaId));
        }

       
        public ActionResult GetCaratulaJSON(int caratulaId)
        {
           
            return new JsonResult
            {
                Data = _repository.GetCaratulaVistaPorId(caratulaId),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet

            };
        }



    }
}

trunk/EasyDoc/Cardinal.EasyApps.ED.Caratulas/App/Cardinal.EasyApps.Caratulas/EasyApps.ED.Caratulas.WebRazor/Views/Caratula/Create.cshtml
@{
    ViewBag.Title = "Alta de Caratula";
}

@section HeaderContent{
<style type="text/css">
      label.error { float: none; color: red; padding-left: .5em; vertical-align: top; }
p { clear: both; }
 .HelperPlantillas
        {
            display:block;
            padding:10px;

  border:1px solid black;
 
  background-color:#EDE8EA; color:#696868;
  text-align: center; 
  font-family:Calibri;
  font-size: small;
        }
         .HelperCampos
        {
            padding-left:100px;padding-bottom:50px;position:relative;
            border:1px solid black;
 
            background-color:#EDE8EA; color:#696868;
            text-align: center; 
             font-family:Calibri;
  font-size: small;
        }
        .field-validation-error { color: red; position: absolute; margin: 0 0 0 5px; }
   .validation-summary-errors {border:1px solid #DFDFDF; background: #FDFDFD; color:Gray;}
    </style>
      <script type="text/javascript">

      function empresaChanged(e) {
            var url = '@Url.Action("_GetPlantillas", "Caratula")';
            var plantillaCombo = $('#Plantilla').data('tComboBox');
            plantillaCombo.loader.showBusy();

            $.get(url, { codEmpresa: e.value }, function (data) {
                plantillaCombo.dataBind(data);
                plantillaCombo.loader.hideBusy();
                plantillaCombo.enable();
            });
        }

        function plantillaChanged(e) {
            var dir = '@Url.Action("GetCamposPlantilla", "Caratula", null)';
            $.ajax({
                url: dir,
                data: { plantillaId: e.value},
                success: function (mydata) {
                    $("#camposPlantilla").empty().append(mydata);
                },
                type: "GET"
            });
        }
        </script>
}

<h2>Alta de Caratula</h2>

@using (Ajax.BeginForm("CreateCaratula", "Caratula",null,null, new { id = "formCaratulas", name = "formCaratulas" }))
{ 
     @Html.ValidationSummary(false, "Imposible generar la caratula. Por favor revise los errores")
      <fieldset style="padding:5px;">
        <legend>Datos de carga</legend>
        <table style="width: 625px">
        <tr>
        <td class="style2">
        <div class="display-label">Empresa</div>
        </td>
        <td class="style3">
            <div class="editor-label">
                  
               @(Html.Telerik().ComboBox().Name("Empresa")
                    .AutoFill(true)
            
.BindTo(new SelectList(ViewBag.Empresas, "CodigoCliente", "Nombre"))
                    .HtmlAttributes(new { style = string.Format("width:300px") })
                    .Filterable(filtering => { filtering.FilterMode(AutoCompleteFilterMode.StartsWith); })
                    .HighlightFirstMatch(true)
                   
                    .ClientEvents(events => events.OnChange("empresaChanged"))

                )
           
        </div></td>
          <td class="style1" rowspan="2">
            <div style="width: 234px" id="HelperPlantillas" class="HelperPlantillas">
             Seleccione empresa y plantilla y luego presione <span style="color:#5772BD; font-weight:bold;">'Cargar Datos'</span>
            </div></td>
        <td class="style1" rowspan="2">
           </td>
        </tr>
        <tr>
        <td class="style2">
       
        <div class="display-label">Plantilla</div>
        
        </td>
        <td class="style3">
         <div class="editor-label">
          @(Html.Telerik().ComboBox().Name("Plantilla")
                    .AutoFill(true)
                    .HtmlAttributes(new { style = string.Format("width:300px") })
                    .Filterable(filtering => { filtering.FilterMode(AutoCompleteFilterMode.StartsWith); })
                    .HighlightFirstMatch(true)
                    .ClientEvents(events => events.OnChange("plantillaChanged"))
                )
        </div>
        </td>
        </tr>
        </table>

            <fieldset>
                <legend>Campos Caratula - Formulario</legend>
                <div id="camposPlantilla">
                </div>
            </fieldset>
               <input type="submit" id="Generar" runat="server" value="Generar reporte" /><br />
    </fieldset>
}

<div>
    @Html.ActionLink("Limpiar formulario", "Index")
</div>

trunk/EasyDoc/Cardinal.EasyApps.ED.Caratulas/App/Cardinal.EasyApps.Caratulas/EasyApps.ED.Caratulas.WebRazor/Views/Caratula/_CamposPlantilla.cshtml
@model List<Cardinal.EasyApps.ED.Model.PlantillaCampo>
          

          
@helper DisplayCampo(Cardinal.EasyApps.ED.Model.PlantillaCampo item)
    {
        switch (item.TipoCampo)
        {
            case Cardinal.EasyApps.ED.Model.TipoCampo.Fecha:
                    @(Html.Telerik().DatePicker().Name(item.CampoId).HtmlAttributes(new { id = "DatePicker_wrapper" }).ShowButton(true))
                break;
            case Cardinal.EasyApps.ED.Model.TipoCampo.Texto:
                if (item.ValoresPosibles.Count() == 0)
                {
                    @Html.TextBox(item.CampoId)
                }
                else
                {
               @(Html.Telerik().ComboBox().Name(item.CampoId)
                    .AutoFill(true)
                    .BindTo(new SelectList(item.ValoresPosibles, "Key", "Value"))
                    .HtmlAttributes(new { style = string.Format("width:300px") })
                    .Filterable(filtering => { filtering.FilterMode(AutoCompleteFilterMode.StartsWith); })
                    .HighlightFirstMatch(true)


                )
                }
                break;
            case Cardinal.EasyApps.ED.Model.TipoCampo.Numero:
                        @(Html.Telerik().NumericTextBox().Name(item.CampoId).Spinners(false)
                            .EmptyMessage("Ingrese Valor").InputHtmlAttributes(new { style = "width:100px" }).DecimalDigits(2))
                    break;
            default:
                    break;
        } 
}

@{
    bool hayDetalle = Model.Where(p => p.EsCampoDetalle == true).Count() > 0;
}

@helper DisplayDetalle(List<Cardinal.EasyApps.ED.Model.PlantillaCampo> model) {
   
    if (true) {
        <text>
        <tr>
            <td colspan="2">
               <fieldset>
                    <legend>Campos Detalle</legend>
                    <div id="camposDetallePlantilla">
                        <table id="campoPlantillaDetalle">
                            <tr >
                            @foreach (var item in model.Where(p => p.EsCampoDetalle == true)){
                                <td>@item.Nombre</td>
                                 <td>  @DisplayCampo(item)</td>
        
                            }
                           
                     </tr>
                    </table>
                    <button id="agregarDetalleButton">Agregar Detalle</button>
                    </div>
                </fieldset>
            </td>
        </tr>
         </text>
    }
}
  
 <script type="text/javascript">
     var i = 1;
     $("#agregarDetalleButton").click(function () {
         $("#campoPlantillaDetalle tr:first").clone().find("input").each(function () {
             var input = $(this).attr({
                 'id': function (_, id) { return id + i },
                 'name': function (_, name) { return name + i },
                 'value': ''
             });

             if (input.parent().hasClass("t-picker-wrap")) {
                 input.tDateTimePicker(); //create DateTimePicker using $.fn.tDateTimePicker.defaults
             }

         }).end().appendTo("#campoPlantillaDetalle");
         i++;
     });
 </script>      
           
<table>
@foreach (var item in Model.Where(p => p.EsCampoDetalle == false))
{
    <tr>
        <td>@item.Nombre
        </td>
         
        <td>
            @DisplayCampo(item)
        </td>
    </tr>
    if (hayDetalle) { 
          @DisplayDetalle(Model)

    }
    
     
}


</table>


